### ISSUE TITLE
need more info

### ISSUE THREAD

**Issue by karimkohel** [TomiVidal99/dPexels#1]
i would love to contribute but can you help by explaining in more details, what exactly is this app supposed to do @TomiVidal99

**Comment by TomiVidal99** [comment]
The idea it's to make an intuitive GUI for people that are not familiarized with coding so they can downlaoad a bunch of images at once from the pexels API (the images would be retrieved accordingly to some word or phrase entered by the user). Hope i was clear enough :). It's a silly project but what ever...

**Comment by karimkohel** [comment]
its a great idea for coding practice and i would love to help

**Comment by TomiVidal99** [comment]
Great! Yeah knock yourself out!

**Comment by karimkohel** [comment]
can you add me to collaborators then in the repo settings under collaborators @TomiVidal99

**Comment by TomiVidal99** [comment]
Done!
